In [2]:
import numpy as np
import random

# 逻辑运算

In [3]:
score = np.random.randint(40, 100, (10, 5))

In [4]:
test_score = score[6:, 0:5]

In [5]:
test_score > 60

array([[False,  True,  True, False,  True],
       [False,  True, False, False, False],
       [ True,  True, False,  True, False],
       [ True, False,  True, False, False]])

In [6]:
test_score[test_score > 60] = 2

In [7]:
test_score

array([[45,  2,  2, 59,  2],
       [46,  2, 47, 42, 50],
       [ 2,  2, 59,  2, 58],
       [ 2, 45,  2, 58, 54]])

In [11]:
score

array([[40, 67, 95, 59, 56],
       [91, 94, 92, 55, 85],
       [49, 56, 72, 96, 45],
       [44, 62, 51, 53, 42],
       [44, 47, 46, 49, 59],
       [75, 40, 85, 75, 77],
       [45,  2,  2, 59,  2],
       [46,  2, 47, 42, 50],
       [ 2,  2, 59,  2, 58],
       [ 2, 45,  2, 58, 54]])

In [13]:
np.all(score[0:2, : ]>60)

False

In [14]:
np.any(score[1,0:3]>90)

True

In [15]:
score[1,0:3]

array([91, 94, 92])

In [17]:
np.where(score[1] > 60, 1, 0)

array([1, 1, 1, 0, 1])

In [18]:
score[1]

array([91, 94, 92, 55, 85])

In [19]:
np.where(np.logical_and(score[0]>30, score[0]<45), 2, 0)

array([2, 0, 0, 0, 0])

In [20]:
np.where(np.logical_or(score[0]<45, score[0]>90), 3, 0)

array([3, 0, 3, 0, 0])

# 数组运算

In [21]:
arr = np.array([[1,2,3,4,5,6],[6,5,4,3,2,1]])

In [22]:
arr + 1

array([[2, 3, 4, 5, 6, 7],
       [7, 6, 5, 4, 3, 2]])

In [23]:
arr / 2

array([[0.5, 1. , 1.5, 2. , 2.5, 3. ],
       [3. , 2.5, 2. , 1.5, 1. , 0.5]])

In [24]:
a = [1, 2, 3, 4, 5]
a * 3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [25]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4, 5, 9], [3, 4, 5, 6, 7, 8]])

In [26]:
arr1 + arr2

array([[ 2,  4,  6,  6,  6, 13],
       [ 8, 10,  6,  8, 10,  9]])

In [27]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [28]:
arr1 + arr2

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

In [29]:
arr1.shape

(2, 6)

In [30]:
arr2.shape

(2, 1)

# 矩阵运算

In [31]:
a = np.array([[80, 86],
              [82, 80],
              [85, 78],
              [90, 90],
              [86, 82],
              [82, 90],
              [78, 80],
              [92, 94]])

In [32]:
b = np.array([[0.7], [0.3]])

In [33]:
np.matmul(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [34]:
np.dot(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [35]:
np.dot(a, 10)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [36]:
np.matmul(a, 10) #matmul不支持矩阵和数字相乘

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

english

english